name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Cloud Storage Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - id: 'upload-files'
      - uses: ptoner/gcp-storage-sync@main
        with:
          args: -d
        env:
          GCP_STORAGE_BUCKET: 'large-reader'
          SOURCE_DIR: "public"
          DEST_DIR: "read-alice"