name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - uses: google-github-actions/deploy-appengine@main